name: ProperWeather
description: Very powerful weather controlling plugin
main: sk.tomsik68.pw.plugin.ProperWeather
author: Tomsik68 <tomsik68@gmail.com>
version: 1.1.7b
commands:
    pw:
        description: ProperWeather base command
        usage: /pw ? for more help :)
        permission: pw.pw