name: ProperWeather
description: Very powerful weather controlling plugin
main: sk.tomsik68.pw.plugin.ProperWeather
author: Tomsik68 <tomsik68@gmail.com>
version: 1.1.6b
commands:
    pw:
        description: /pw for more info ;)
        usage: /pw <sub-command> <parameters>
        permission: pw.pw